### ISSUE TITLE
fatal: Needed a single revision

### ISSUE THREAD

**Issue by dillongreen** [devCharles/gitRepoUpdater#4]
running it I get two lines of `fatal: Needed a single revision` for each repo.

**Comment by devCharles** [comment]
hi @dillongreen , the script is trying to update your repositories in 2 different branches: 'develop' and 'master' if you have develop then master won't be updated, otherwise if develop does not exists master will be update but both are requested, so if you don't have a remote or history to be fetched from it, you will get this message, it is printed 2 times because of each attempt in different branches

please make sure you have a remote in your repositories and if you do, if the remote repos are not empty
